#cloud-config
hostname: ${hostname}

reporting:
  logging:
    type: log
    level: DEBUG

users:
  - default
  - name: ${username}
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL

chpasswd:
  list: |
    ${username}:ubuntu
  expire: True

package_update: true
packages:
  - qemu-guest-agent
  - net-tools

runcmd:
  - timedatectl set-timezone Europe/Rome
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent